spring:
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER}:3306/mydb
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL

flyway:
  enabled: true
  schema: mydb
  user: root
  password: ${MYSQL_PASSWORD}
